# Generated by Django 2.2 on 2022-04-26 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='universal',
            field=models.CharField(default='', max_length=255),
        ),
    ]
