# Generated by Django 2.2 on 2022-04-29 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0005_auto_20220429_0837'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilefeeditem',
            old_name='changed_od',
            new_name='changed_on',
        ),
    ]
